[extend]
useDefault = true

[allowlist]
paths = [
    '''\.secrets\.baseline''',
    '''tests/cases/diff/kubernetes/k8s_406_secret_reference\.yaml''',
    '''tests/cases/diff/kubernetes/k8s_418_image_pull_secret\.yaml''',
    '''tests/cases/diff/algorithm/algorithm_004_fragment_markdown_section_diffctx\.yaml''',
    '''tests/cases/diff/docker/docker_039_compose_secrets_before\.yaml''',
    '''tests/cases/diff/docker/docker_039_compose_secrets_after\.yaml''',
    '''tests/cases/diff/fragments/fragments_018_config_yaml_top_level_keys_before\.yaml''',
    '''tests/cases/diff/fragments/fragments_018_config_yaml_top_level_keys_after\.yaml''',
]
