[extend]
useDefault = true

[allowlist]
paths = [
    '''\.secrets\.baseline''',
    '''tests/cases/diff/kubernetes/k8s_406_secret_reference\.yaml''',
    '''tests/cases/diff/kubernetes/k8s_418_image_pull_secret\.yaml''',
]
